Tab completion
rosberry/depo pull request #15
Opened 2020-12-14 04:34 UTC by zhvrnkov

#13 
### Description
What were done in this PR:
1. specify completion for all command line arguments
2. add abstract description to every command
3. update CartfileParser -- remove `scanUpTo` calls
4. Fix Linux build

### Checklist

- [x] Follows code style
- [x] Has no SwiftLint warnings
- [ ] Covered by tests
- [ ] All tests are passed
- [x] Access control words were checked

2021-01-14 10:52 UTC, Tublad requested changes

2021-01-14 10:52 UTC, Tublad commented on Sources/CartfileParser/CarthageVersion.swift
> +    }
```suggestion
        private var numericValue: Int? {
            if !self.isEmpty,
                self.rangeOfCharacter(from: SemanticVersion.semVerDecimalDigits.inverted) == nil {
                return Int(self)
            }
            return nil
        }
```

2021-01-14 10:52 UTC, Tublad commented on Sources/CartfileParser/CarthageVersion.swift
> +        }
```suggestion
        if lv.major == 0,
           rv.major == 0 {
            if lv.minor != rv.minor {
                return nil
            }
        }
```

2021-01-20 10:49 UTC, Tublad approved these changes

2021-01-20 11:18 UTC, merged

2021-01-20 11:19 UTC, zhvrnkov commented
Merged with single approve since #16 were reviewed before (#16 includes changes from this PR)