20
rosberry/depo pull request #23
Opened 2021-01-21 09:41 UTC by zhvrnkov

#20

### Description
In this PR:
- Allow to use `--cache-builds` flag for `carthage` command
- Add "free form" argument for each package manager. In other words, allow to specify arguments, which aren't handled by depo

### Checklist

- [x] Follows code style
- [x] Has no SwiftLint warnings
- [ ] Covered by tests
- [ ] All tests are passed
- [x] Access control words were checked

2021-02-03 07:28 UTC, stason314 requested changes

2021-02-03 07:28 UTC, stason314 commented on Sources/DepoCore/Helpers/Bool+Map.swift
> +        }
```suggestion
        self ? value : nil
```

2021-02-03 07:28 UTC, stason314 commented on Sources/DepoCore/Helpers/Optional+Convenience.swift
> +    func map<T>(keyPath: KeyPath<Wrapped, T>) -> T? {
Which case of using this func? 
`optional?.value` will gives same effect isn't it?

2021-02-03 07:36 UTC, stason314 approved these changes

2021-02-04 04:42 UTC, ntunin approved these changes

2021-02-04 05:20 UTC, Tublad approved these changes

2021-02-04 11:02 UTC, merged